graph TD
  n0["and"]
  n1["and"]
  n2["and"]
  n3["and"]
  n4["and"]
  n5["and"]
  n6["and"]
  n7["and"]
  n8["and"]
  n9["and"]
  n10["and"]
  n11["and"]
  n12["or"]
  n13["and"]
  n14["houses.0.sport === &quot;Bowling&quot;"]
  n13 --> n14
  n15["houses.3.sport === &quot;Swimming&quot;"]
  n13 --> n15
  n12 --> n13
  n16["and"]
  n17["houses.3.sport === &quot;Bowling&quot;"]
  n16 --> n17
  n18["houses.0.sport === &quot;Swimming&quot;"]
  n16 --> n18
  n12 --> n16
  n11 --> n12
  n19["or"]
  n20["and"]
  n21["houses.0.sport === &quot;Handball&quot;"]
  n20 --> n21
  n22["houses.2.nationality === &quot;Irish&quot;"]
  n20 --> n22
  n19 --> n20
  n23["and"]
  n24["houses.1.sport === &quot;Handball&quot;"]
  n23 --> n24
  n25["houses.3.nationality === &quot;Irish&quot;"]
  n23 --> n25
  n19 --> n23
  n11 --> n19
  n10 --> n11
  n26["houses.1.color === &quot;Black&quot;"]
  n10 --> n26
  n9 --> n10
  n27["or"]
  n28["and"]
  n29["houses.0.animal === &quot;Horses&quot;"]
  n28 --> n29
  n30["houses.2.color === &quot;Red&quot;"]
  n28 --> n30
  n27 --> n28
  n31["and"]
  n32["houses.1.animal === &quot;Horses&quot;"]
  n31 --> n32
  n33["houses.3.color === &quot;Red&quot;"]
  n31 --> n33
  n27 --> n31
  n9 --> n27
  n8 --> n9
  n34["or"]
  n35["or"]
  n36["and"]
  n37["houses.0.nationality === &quot;American&quot;"]
  n36 --> n37
  n38["houses.1.animal === &quot;Turtles&quot;"]
  n36 --> n38
  n35 --> n36
  n39["and"]
  n40["houses.1.nationality === &quot;American&quot;"]
  n39 --> n40
  n41["houses.2.animal === &quot;Turtles&quot;"]
  n39 --> n41
  n35 --> n39
  n34 --> n35
  n42["and"]
  n43["houses.2.nationality === &quot;American&quot;"]
  n42 --> n43
  n44["houses.3.animal === &quot;Turtles&quot;"]
  n42 --> n44
  n34 --> n42
  n8 --> n34
  n7 --> n8
  n45["and"]
  n46["houses.0.animal === &quot;Horses&quot;"]
  n45 --> n46
  n47["houses.3.animal === &quot;Butterflies&quot;"]
  n45 --> n47
  n7 --> n45
  n6 --> n7
  n48["or"]
  n49["or"]
  n50["or"]
  n51["or"]
  n52["or"]
  n53["and"]
  n54["houses.0.sport === &quot;Tennis&quot;"]
  n53 --> n54
  n55["houses.1.sport === &quot;Bowling&quot;"]
  n53 --> n55
  n52 --> n53
  n56["and"]
  n57["houses.0.sport === &quot;Tennis&quot;"]
  n56 --> n57
  n58["houses.2.sport === &quot;Bowling&quot;"]
  n56 --> n58
  n52 --> n56
  n51 --> n52
  n59["and"]
  n60["houses.0.sport === &quot;Tennis&quot;"]
  n59 --> n60
  n61["houses.3.sport === &quot;Bowling&quot;"]
  n59 --> n61
  n51 --> n59
  n50 --> n51
  n62["and"]
  n63["houses.1.sport === &quot;Tennis&quot;"]
  n62 --> n63
  n64["houses.2.sport === &quot;Bowling&quot;"]
  n62 --> n64
  n50 --> n62
  n49 --> n50
  n65["and"]
  n66["houses.1.sport === &quot;Tennis&quot;"]
  n65 --> n66
  n67["houses.3.sport === &quot;Bowling&quot;"]
  n65 --> n67
  n49 --> n65
  n48 --> n49
  n68["and"]
  n69["houses.2.sport === &quot;Tennis&quot;"]
  n68 --> n69
  n70["houses.3.sport === &quot;Bowling&quot;"]
  n68 --> n70
  n48 --> n68
  n6 --> n48
  n5 --> n6
  n71["or"]
  n72["and"]
  n73["houses.0.sport === &quot;Handball&quot;"]
  n72 --> n73
  n74["houses.2.color === &quot;White&quot;"]
  n72 --> n74
  n71 --> n72
  n75["and"]
  n76["houses.1.sport === &quot;Handball&quot;"]
  n75 --> n76
  n77["houses.3.color === &quot;White&quot;"]
  n75 --> n77
  n71 --> n75
  n5 --> n71
  n4 --> n5
  n78["houses.0.nationality === &quot;British&quot;"]
  n4 --> n78
  n3 --> n4
  n79["and"]
  n80["and"]
  n81["and"]
  n82["and"]
  n83["and"]
  n84["houses.0.color !== houses.1.color"]
  n83 --> n84
  n85["houses.0.color !== houses.2.color"]
  n83 --> n85
  n82 --> n83
  n86["houses.0.color !== houses.3.color"]
  n82 --> n86
  n81 --> n82
  n87["houses.1.color !== houses.2.color"]
  n81 --> n87
  n80 --> n81
  n88["houses.1.color !== houses.3.color"]
  n80 --> n88
  n79 --> n80
  n89["houses.2.color !== houses.3.color"]
  n79 --> n89
  n3 --> n79
  n2 --> n3
  n90["and"]
  n91["and"]
  n92["and"]
  n93["and"]
  n94["and"]
  n95["houses.0.nationality !== houses.1.nationality"]
  n94 --> n95
  n96["houses.0.nationality !== houses.2.nationality"]
  n94 --> n96
  n93 --> n94
  n97["houses.0.nationality !== houses.3.nationality"]
  n93 --> n97
  n92 --> n93
  n98["houses.1.nationality !== houses.2.nationality"]
  n92 --> n98
  n91 --> n92
  n99["houses.1.nationality !== houses.3.nationality"]
  n91 --> n99
  n90 --> n91
  n100["houses.2.nationality !== houses.3.nationality"]
  n90 --> n100
  n2 --> n90
  n1 --> n2
  n101["and"]
  n102["and"]
  n103["and"]
  n104["and"]
  n105["and"]
  n106["houses.0.animal !== houses.1.animal"]
  n105 --> n106
  n107["houses.0.animal !== houses.2.animal"]
  n105 --> n107
  n104 --> n105
  n108["houses.0.animal !== houses.3.animal"]
  n104 --> n108
  n103 --> n104
  n109["houses.1.animal !== houses.2.animal"]
  n103 --> n109
  n102 --> n103
  n110["houses.1.animal !== houses.3.animal"]
  n102 --> n110
  n101 --> n102
  n111["houses.2.animal !== houses.3.animal"]
  n101 --> n111
  n1 --> n101
  n0 --> n1
  n112["and"]
  n113["and"]
  n114["and"]
  n115["and"]
  n116["and"]
  n117["houses.0.sport !== houses.1.sport"]
  n116 --> n117
  n118["houses.0.sport !== houses.2.sport"]
  n116 --> n118
  n115 --> n116
  n119["houses.0.sport !== houses.3.sport"]
  n115 --> n119
  n114 --> n115
  n120["houses.1.sport !== houses.2.sport"]
  n114 --> n120
  n113 --> n114
  n121["houses.1.sport !== houses.3.sport"]
  n113 --> n121
  n112 --> n113
  n122["houses.2.sport !== houses.3.sport"]
  n112 --> n122
  n0 --> n112