graph TD
  n0["and"]
  n1["and"]
  n2["and"]
  n3["and"]
  n4["or"]
  n5["and"]
  n6["houses.0.color === &quot;Red&quot;"]
  n5 --> n6
  n7["houses.1.nationality === &quot;Spanish&quot;"]
  n5 --> n7
  n4 --> n5
  n8["and"]
  n9["houses.1.color === &quot;Red&quot;"]
  n8 --> n9
  n10["houses.2.nationality === &quot;Spanish&quot;"]
  n8 --> n10
  n4 --> n8
  n3 --> n4
  n11["or"]
  n12["or"]
  n13["and"]
  n14["houses.0.color === &quot;Blue&quot;"]
  n13 --> n14
  n15["houses.0.nationality === &quot;Norwegian&quot;"]
  n13 --> n15
  n12 --> n13
  n16["and"]
  n17["houses.1.color === &quot;Blue&quot;"]
  n16 --> n17
  n18["houses.1.nationality === &quot;Norwegian&quot;"]
  n16 --> n18
  n12 --> n16
  n11 --> n12
  n19["and"]
  n20["houses.2.color === &quot;Blue&quot;"]
  n19 --> n20
  n21["houses.2.nationality === &quot;Norwegian&quot;"]
  n19 --> n21
  n11 --> n19
  n3 --> n11
  n2 --> n3
  n22["houses.1.nationality === &quot;Italian&quot;"]
  n2 --> n22
  n1 --> n2
  n23["and"]
  n24["and"]
  n25["houses.0.nationality !== houses.1.nationality"]
  n24 --> n25
  n26["houses.0.nationality !== houses.2.nationality"]
  n24 --> n26
  n23 --> n24
  n27["houses.1.nationality !== houses.2.nationality"]
  n23 --> n27
  n1 --> n23
  n0 --> n1
  n28["and"]
  n29["and"]
  n30["houses.0.color !== houses.1.color"]
  n29 --> n30
  n31["houses.0.color !== houses.2.color"]
  n29 --> n31
  n28 --> n29
  n32["houses.1.color !== houses.2.color"]
  n28 --> n32
  n0 --> n28