mindmap
  root((and))
    and
      and
        and
          and
            and
              and
                and
                  and
                    and
                      and
                        and
                          or
                            and
                              houses.0.sport === &quot;Bowling&quot;
                              houses.3.sport === &quot;Swimming&quot;
                            and
                              houses.3.sport === &quot;Bowling&quot;
                              houses.0.sport === &quot;Swimming&quot;
                          or
                            and
                              houses.0.sport === &quot;Handball&quot;
                              houses.2.nationality === &quot;Irish&quot;
                            and
                              houses.1.sport === &quot;Handball&quot;
                              houses.3.nationality === &quot;Irish&quot;
                        houses.1.color === &quot;Black&quot;
                      or
                        and
                          houses.0.animal === &quot;Horses&quot;
                          houses.2.color === &quot;Red&quot;
                        and
                          houses.1.animal === &quot;Horses&quot;
                          houses.3.color === &quot;Red&quot;
                    or
                      or
                        and
                          houses.0.nationality === &quot;American&quot;
                          houses.1.animal === &quot;Turtles&quot;
                        and
                          houses.1.nationality === &quot;American&quot;
                          houses.2.animal === &quot;Turtles&quot;
                      and
                        houses.2.nationality === &quot;American&quot;
                        houses.3.animal === &quot;Turtles&quot;
                  and
                    houses.0.animal === &quot;Horses&quot;
                    houses.3.animal === &quot;Butterflies&quot;
                or
                  or
                    or
                      or
                        or
                          and
                            houses.0.sport === &quot;Tennis&quot;
                            houses.1.sport === &quot;Bowling&quot;
                          and
                            houses.0.sport === &quot;Tennis&quot;
                            houses.2.sport === &quot;Bowling&quot;
                        and
                          houses.0.sport === &quot;Tennis&quot;
                          houses.3.sport === &quot;Bowling&quot;
                      and
                        houses.1.sport === &quot;Tennis&quot;
                        houses.2.sport === &quot;Bowling&quot;
                    and
                      houses.1.sport === &quot;Tennis&quot;
                      houses.3.sport === &quot;Bowling&quot;
                  and
                    houses.2.sport === &quot;Tennis&quot;
                    houses.3.sport === &quot;Bowling&quot;
              or
                and
                  houses.0.sport === &quot;Handball&quot;
                  houses.2.color === &quot;White&quot;
                and
                  houses.1.sport === &quot;Handball&quot;
                  houses.3.color === &quot;White&quot;
            houses.0.nationality === &quot;British&quot;
          and
            and
              and
                and
                  and
                    houses.0.color !== houses.1.color
                    houses.0.color !== houses.2.color
                  houses.0.color !== houses.3.color
                houses.1.color !== houses.2.color
              houses.1.color !== houses.3.color
            houses.2.color !== houses.3.color
        and
          and
            and
              and
                and
                  houses.0.nationality !== houses.1.nationality
                  houses.0.nationality !== houses.2.nationality
                houses.0.nationality !== houses.3.nationality
              houses.1.nationality !== houses.2.nationality
            houses.1.nationality !== houses.3.nationality
          houses.2.nationality !== houses.3.nationality
      and
        and
          and
            and
              and
                houses.0.animal !== houses.1.animal
                houses.0.animal !== houses.2.animal
              houses.0.animal !== houses.3.animal
            houses.1.animal !== houses.2.animal
          houses.1.animal !== houses.3.animal
        houses.2.animal !== houses.3.animal
    and
      and
        and
          and
            and
              houses.0.sport !== houses.1.sport
              houses.0.sport !== houses.2.sport
            houses.0.sport !== houses.3.sport
          houses.1.sport !== houses.2.sport
        houses.1.sport !== houses.3.sport
      houses.2.sport !== houses.3.sport