flowchart LR
  f0(("or"))
  v0["houses.0.sport"]
  f0 --- v0
  v1["houses.3.sport"]
  f0 --- v1
  f1(("or"))
  f1 --- v0
  v2["houses.1.sport"]
  f1 --- v2
  v3["houses.2.nationality"]
  f1 --- v3
  v4["houses.3.nationality"]
  f1 --- v4
  f2(("houses.1.color === &quot;Black&quot;"))
  v5["houses.1.color"]
  f2 --- v5
  f3(("or"))
  v6["houses.0.animal"]
  f3 --- v6
  v7["houses.1.animal"]
  f3 --- v7
  v8["houses.2.color"]
  f3 --- v8
  v9["houses.3.color"]
  f3 --- v9
  f4(("or"))
  v10["houses.0.nationality"]
  f4 --- v10
  f4 --- v7
  v11["houses.1.nationality"]
  f4 --- v11
  v12["houses.2.animal"]
  f4 --- v12
  f4 --- v3
  v13["houses.3.animal"]
  f4 --- v13
  f5(("houses.0.animal === &quot;Horses&quot;"))
  f5 --- v6
  f6(("houses.3.animal === &quot;Butterflies&quot;"))
  f6 --- v13
  f7(("or"))
  f7 --- v0
  f7 --- v2
  v14["houses.2.sport"]
  f7 --- v14
  f7 --- v1
  f8(("or"))
  f8 --- v0
  f8 --- v2
  f8 --- v8
  f8 --- v9
  f9(("houses.0.nationality === &quot;British&quot;"))
  f9 --- v10
  f10(("houses.0.color !== houses.1.color"))
  v15["houses.0.color"]
  f10 --- v15
  f10 --- v5
  f11(("houses.0.color !== houses.2.color"))
  f11 --- v15
  f11 --- v8
  f12(("houses.0.color !== houses.3.color"))
  f12 --- v15
  f12 --- v9
  f13(("houses.1.color !== houses.2.color"))
  f13 --- v5
  f13 --- v8
  f14(("houses.1.color !== houses.3.color"))
  f14 --- v5
  f14 --- v9
  f15(("houses.2.color !== houses.3.color"))
  f15 --- v8
  f15 --- v9
  f16(("houses.0.nationality !== houses.1.nationality"))
  f16 --- v10
  f16 --- v11
  f17(("houses.0.nationality !== houses.2.nationality"))
  f17 --- v10
  f17 --- v3
  f18(("houses.0.nationality !== houses.3.nationality"))
  f18 --- v10
  f18 --- v4
  f19(("houses.1.nationality !== houses.2.nationality"))
  f19 --- v11
  f19 --- v3
  f20(("houses.1.nationality !== houses.3.nationality"))
  f20 --- v11
  f20 --- v4
  f21(("houses.2.nationality !== houses.3.nationality"))
  f21 --- v3
  f21 --- v4
  f22(("houses.0.animal !== houses.1.animal"))
  f22 --- v6
  f22 --- v7
  f23(("houses.0.animal !== houses.2.animal"))
  f23 --- v6
  f23 --- v12
  f24(("houses.0.animal !== houses.3.animal"))
  f24 --- v6
  f24 --- v13
  f25(("houses.1.animal !== houses.2.animal"))
  f25 --- v7
  f25 --- v12
  f26(("houses.1.animal !== houses.3.animal"))
  f26 --- v7
  f26 --- v13
  f27(("houses.2.animal !== houses.3.animal"))
  f27 --- v12
  f27 --- v13
  f28(("houses.0.sport !== houses.1.sport"))
  f28 --- v0
  f28 --- v2
  f29(("houses.0.sport !== houses.2.sport"))
  f29 --- v0
  f29 --- v14
  f30(("houses.0.sport !== houses.3.sport"))
  f30 --- v0
  f30 --- v1
  f31(("houses.1.sport !== houses.2.sport"))
  f31 --- v2
  f31 --- v14
  f32(("houses.1.sport !== houses.3.sport"))
  f32 --- v2
  f32 --- v1
  f33(("houses.2.sport !== houses.3.sport"))
  f33 --- v14
  f33 --- v1