graph TD
  n0["and"]
  n1["and"]
  n2["and"]
  n3["and"]
  n4["and"]
  n5["and"]
  n6["and"]
  n7["and"]
  n8["and"]
  n9["houses.1.nationality !== &quot;Brazilian&quot;"]
  n8 --> n9
  n10["or"]
  n11["or"]
  n12["and"]
  n13["houses.0.animal === &quot;Dog&quot;"]
  n12 --> n13
  n14["houses.0.sport === &quot;Basketball&quot;"]
  n12 --> n14
  n11 --> n12
  n15["and"]
  n16["houses.1.animal === &quot;Dog&quot;"]
  n15 --> n16
  n17["houses.1.sport === &quot;Basketball&quot;"]
  n15 --> n17
  n11 --> n15
  n10 --> n11
  n18["and"]
  n19["houses.2.animal === &quot;Dog&quot;"]
  n18 --> n19
  n20["houses.2.sport === &quot;Basketball&quot;"]
  n18 --> n20
  n10 --> n18
  n8 --> n10
  n7 --> n8
  n21["and"]
  n22["houses.0.sport === &quot;Football&quot;"]
  n21 --> n22
  n23["houses.2.color === &quot;Red&quot;"]
  n21 --> n23
  n7 --> n21
  n6 --> n7
  n24["or"]
  n25["and"]
  n26["houses.0.animal === &quot;Fish&quot;"]
  n25 --> n26
  n27["houses.1.animal === &quot;Cat&quot;"]
  n25 --> n27
  n24 --> n25
  n28["and"]
  n29["houses.1.animal === &quot;Fish&quot;"]
  n28 --> n29
  n30["houses.2.animal === &quot;Cat&quot;"]
  n28 --> n30
  n24 --> n28
  n6 --> n24
  n5 --> n6
  n31["or"]
  n32["and"]
  n33["houses.0.color === &quot;Green&quot;"]
  n32 --> n33
  n34["houses.1.animal === &quot;Dog&quot;"]
  n32 --> n34
  n31 --> n32
  n35["and"]
  n36["houses.1.color === &quot;Green&quot;"]
  n35 --> n36
  n37["houses.2.animal === &quot;Dog&quot;"]
  n35 --> n37
  n31 --> n35
  n5 --> n31
  n4 --> n5
  n38["houses.2.nationality === &quot;German&quot;"]
  n4 --> n38
  n3 --> n4
  n39["and"]
  n40["and"]
  n41["houses.0.color !== houses.1.color"]
  n40 --> n41
  n42["houses.0.color !== houses.2.color"]
  n40 --> n42
  n39 --> n40
  n43["houses.1.color !== houses.2.color"]
  n39 --> n43
  n3 --> n39
  n2 --> n3
  n44["and"]
  n45["and"]
  n46["houses.0.nationality !== houses.1.nationality"]
  n45 --> n46
  n47["houses.0.nationality !== houses.2.nationality"]
  n45 --> n47
  n44 --> n45
  n48["houses.1.nationality !== houses.2.nationality"]
  n44 --> n48
  n2 --> n44
  n1 --> n2
  n49["and"]
  n50["and"]
  n51["houses.0.animal !== houses.1.animal"]
  n50 --> n51
  n52["houses.0.animal !== houses.2.animal"]
  n50 --> n52
  n49 --> n50
  n53["houses.1.animal !== houses.2.animal"]
  n49 --> n53
  n1 --> n49
  n0 --> n1
  n54["and"]
  n55["and"]
  n56["houses.0.sport !== houses.1.sport"]
  n55 --> n56
  n57["houses.0.sport !== houses.2.sport"]
  n55 --> n57
  n54 --> n55
  n58["houses.1.sport !== houses.2.sport"]
  n54 --> n58
  n0 --> n54