graph TD
  n0["and"]
  n1["and"]
  n2["and"]
  n3["and"]
  n4["and"]
  n5["and"]
  n6["and"]
  n7["and"]
  n8["and"]
  n9["!=="]
  n10["houses.1.nationality"]
  n9 --> n10
  n11["&quot;Brazilian&quot;"]
  n9 --> n11
  n8 --> n9
  n12["or"]
  n13["or"]
  n14["and"]
  n15["==="]
  n16["houses.0.animal"]
  n15 --> n16
  n17["&quot;Dog&quot;"]
  n15 --> n17
  n14 --> n15
  n18["==="]
  n19["houses.0.sport"]
  n18 --> n19
  n20["&quot;Basketball&quot;"]
  n18 --> n20
  n14 --> n18
  n13 --> n14
  n21["and"]
  n22["==="]
  n23["houses.1.animal"]
  n22 --> n23
  n24["&quot;Dog&quot;"]
  n22 --> n24
  n21 --> n22
  n25["==="]
  n26["houses.1.sport"]
  n25 --> n26
  n27["&quot;Basketball&quot;"]
  n25 --> n27
  n21 --> n25
  n13 --> n21
  n12 --> n13
  n28["and"]
  n29["==="]
  n30["houses.2.animal"]
  n29 --> n30
  n31["&quot;Dog&quot;"]
  n29 --> n31
  n28 --> n29
  n32["==="]
  n33["houses.2.sport"]
  n32 --> n33
  n34["&quot;Basketball&quot;"]
  n32 --> n34
  n28 --> n32
  n12 --> n28
  n8 --> n12
  n7 --> n8
  n35["and"]
  n36["==="]
  n37["houses.0.sport"]
  n36 --> n37
  n38["&quot;Football&quot;"]
  n36 --> n38
  n35 --> n36
  n39["==="]
  n40["houses.2.color"]
  n39 --> n40
  n41["&quot;Red&quot;"]
  n39 --> n41
  n35 --> n39
  n7 --> n35
  n6 --> n7
  n42["or"]
  n43["and"]
  n44["==="]
  n45["houses.0.animal"]
  n44 --> n45
  n46["&quot;Fish&quot;"]
  n44 --> n46
  n43 --> n44
  n47["==="]
  n48["houses.1.animal"]
  n47 --> n48
  n49["&quot;Cat&quot;"]
  n47 --> n49
  n43 --> n47
  n42 --> n43
  n50["and"]
  n51["==="]
  n52["houses.1.animal"]
  n51 --> n52
  n53["&quot;Fish&quot;"]
  n51 --> n53
  n50 --> n51
  n54["==="]
  n55["houses.2.animal"]
  n54 --> n55
  n56["&quot;Cat&quot;"]
  n54 --> n56
  n50 --> n54
  n42 --> n50
  n6 --> n42
  n5 --> n6
  n57["or"]
  n58["and"]
  n59["==="]
  n60["houses.0.color"]
  n59 --> n60
  n61["&quot;Green&quot;"]
  n59 --> n61
  n58 --> n59
  n62["==="]
  n63["houses.1.animal"]
  n62 --> n63
  n64["&quot;Dog&quot;"]
  n62 --> n64
  n58 --> n62
  n57 --> n58
  n65["and"]
  n66["==="]
  n67["houses.1.color"]
  n66 --> n67
  n68["&quot;Green&quot;"]
  n66 --> n68
  n65 --> n66
  n69["==="]
  n70["houses.2.animal"]
  n69 --> n70
  n71["&quot;Dog&quot;"]
  n69 --> n71
  n65 --> n69
  n57 --> n65
  n5 --> n57
  n4 --> n5
  n72["==="]
  n73["houses.2.nationality"]
  n72 --> n73
  n74["&quot;German&quot;"]
  n72 --> n74
  n4 --> n72
  n3 --> n4
  n75["and"]
  n76["and"]
  n77["!=="]
  n78["houses.0.color"]
  n77 --> n78
  n79["houses.1.color"]
  n77 --> n79
  n76 --> n77
  n80["!=="]
  n81["houses.0.color"]
  n80 --> n81
  n82["houses.2.color"]
  n80 --> n82
  n76 --> n80
  n75 --> n76
  n83["!=="]
  n84["houses.1.color"]
  n83 --> n84
  n85["houses.2.color"]
  n83 --> n85
  n75 --> n83
  n3 --> n75
  n2 --> n3
  n86["and"]
  n87["and"]
  n88["!=="]
  n89["houses.0.nationality"]
  n88 --> n89
  n90["houses.1.nationality"]
  n88 --> n90
  n87 --> n88
  n91["!=="]
  n92["houses.0.nationality"]
  n91 --> n92
  n93["houses.2.nationality"]
  n91 --> n93
  n87 --> n91
  n86 --> n87
  n94["!=="]
  n95["houses.1.nationality"]
  n94 --> n95
  n96["houses.2.nationality"]
  n94 --> n96
  n86 --> n94
  n2 --> n86
  n1 --> n2
  n97["and"]
  n98["and"]
  n99["!=="]
  n100["houses.0.animal"]
  n99 --> n100
  n101["houses.1.animal"]
  n99 --> n101
  n98 --> n99
  n102["!=="]
  n103["houses.0.animal"]
  n102 --> n103
  n104["houses.2.animal"]
  n102 --> n104
  n98 --> n102
  n97 --> n98
  n105["!=="]
  n106["houses.1.animal"]
  n105 --> n106
  n107["houses.2.animal"]
  n105 --> n107
  n97 --> n105
  n1 --> n97
  n0 --> n1
  n108["and"]
  n109["and"]
  n110["!=="]
  n111["houses.0.sport"]
  n110 --> n111
  n112["houses.1.sport"]
  n110 --> n112
  n109 --> n110
  n113["!=="]
  n114["houses.0.sport"]
  n113 --> n114
  n115["houses.2.sport"]
  n113 --> n115
  n109 --> n113
  n108 --> n109
  n116["!=="]
  n117["houses.1.sport"]
  n116 --> n117
  n118["houses.2.sport"]
  n116 --> n118
  n108 --> n116
  n0 --> n108