flowchart LR
  f0(("houses.1.nationality !== &quot;Brazilian&quot;"))
  v0["houses.1.nationality"]
  f0 --- v0
  f1(("or"))
  v1["houses.0.animal"]
  f1 --- v1
  v2["houses.0.sport"]
  f1 --- v2
  v3["houses.1.animal"]
  f1 --- v3
  v4["houses.1.sport"]
  f1 --- v4
  v5["houses.2.animal"]
  f1 --- v5
  v6["houses.2.sport"]
  f1 --- v6
  f2(("houses.0.sport === &quot;Football&quot;"))
  f2 --- v2
  f3(("houses.2.color === &quot;Red&quot;"))
  v7["houses.2.color"]
  f3 --- v7
  f4(("or"))
  f4 --- v1
  f4 --- v3
  f4 --- v5
  f5(("or"))
  v8["houses.0.color"]
  f5 --- v8
  f5 --- v3
  v9["houses.1.color"]
  f5 --- v9
  f5 --- v5
  f6(("houses.2.nationality === &quot;German&quot;"))
  v10["houses.2.nationality"]
  f6 --- v10
  f7(("houses.0.color !== houses.1.color"))
  f7 --- v8
  f7 --- v9
  f8(("houses.0.color !== houses.2.color"))
  f8 --- v8
  f8 --- v7
  f9(("houses.1.color !== houses.2.color"))
  f9 --- v9
  f9 --- v7
  f10(("houses.0.nationality !== houses.1.nationality"))
  v11["houses.0.nationality"]
  f10 --- v11
  f10 --- v0
  f11(("houses.0.nationality !== houses.2.nationality"))
  f11 --- v11
  f11 --- v10
  f12(("houses.1.nationality !== houses.2.nationality"))
  f12 --- v0
  f12 --- v10
  f13(("houses.0.animal !== houses.1.animal"))
  f13 --- v1
  f13 --- v3
  f14(("houses.0.animal !== houses.2.animal"))
  f14 --- v1
  f14 --- v5
  f15(("houses.1.animal !== houses.2.animal"))
  f15 --- v3
  f15 --- v5
  f16(("houses.0.sport !== houses.1.sport"))
  f16 --- v2
  f16 --- v4
  f17(("houses.0.sport !== houses.2.sport"))
  f17 --- v2
  f17 --- v6
  f18(("houses.1.sport !== houses.2.sport"))
  f18 --- v4
  f18 --- v6