flowchart LR
  f0(("or"))
  v0["houses.0.color"]
  f0 --- v0
  v1["houses.1.color"]
  f0 --- v1
  v2["houses.1.nationality"]
  f0 --- v2
  v3["houses.2.nationality"]
  f0 --- v3
  f1(("or"))
  f1 --- v0
  v4["houses.0.nationality"]
  f1 --- v4
  f1 --- v1
  f1 --- v2
  v5["houses.2.color"]
  f1 --- v5
  f1 --- v3
  f2(("houses.1.nationality === &quot;Italian&quot;"))
  f2 --- v2
  f3(("houses.0.nationality !== houses.1.nationality"))
  f3 --- v4
  f3 --- v2
  f4(("houses.0.nationality !== houses.2.nationality"))
  f4 --- v4
  f4 --- v3
  f5(("houses.1.nationality !== houses.2.nationality"))
  f5 --- v2
  f5 --- v3
  f6(("houses.0.color !== houses.1.color"))
  f6 --- v0
  f6 --- v1
  f7(("houses.0.color !== houses.2.color"))
  f7 --- v0
  f7 --- v5
  f8(("houses.1.color !== houses.2.color"))
  f8 --- v1
  f8 --- v5