name: CI
on:
    push:
        branches:
            - "**" # matches every branch
            - "!main" # excludes master

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install dependencies
              uses: ./.github/actions/setup

            - run: pnpm run ci
            - run: pnpm run docs
